apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:  
  name: cd-pipeline
spec:
  workspaces:
    - name: pipeline-workspace
    - name: maven-settings
      optional: true
  params:
    - name: repo-url
    - name: branch
      default: main
    - name: maven-args
      description: Arguments to pass to Maven
      default: "clean package"
  tasks:
    - name: init
      workspaces:
        - name: source
          workspace: pipeline-workspace          
      taskRef:
        name: cleanup

    - name: clone
      workspaces:
        - name: output
          workspace: pipeline-workspace          
      taskRef:
        name: git-clone
      params:
      - name: url
        value: $(params.repo-url)
      - name: revision
        value: $(params.branch)
      runAfter:
        - init      

    - name: lint
      workspaces:
        - name: source
          workspace: pipeline-workspace
        - name: maven-settings
          workspace: maven-settings          
      taskRef:
        name: checkstyle
      runAfter:
        - clone

    - name: tests
      workspaces:
        - name: source
          workspace: pipeline-workspace
        - name: maven-settings
          workspace: maven-settings          
      taskRef:
        name: maven-test
      params:
      - name: maven-args
        value: "verify -Dmaven.test.failure.ignore=false"
      runAfter:
        - lint

    - name: build
      taskRef:
        name: echo
      params:
      - name: message
        value: "Building image for $(params.repo-url) ..."
      - name: DOCKERFILE
        value: "./Dockerfile"
      runAfter:
        - tests

    - name: deploy
      taskRef:
        name: echo
      params:
      - name: message
        value: "Deploying $(params.branch) branch of $(params.repo-url) ..."
      runAfter:
        - build