apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: echo
spec:
  params:
    - name: message
      description: The message to echo
      type: string
  steps:
    - name: echo-message
      image: alpine:3
      command: [/bin/echo]
      args: ["$(params.message)"]

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  description: This task will clean up a workspace by deleting all of the files.
  workspaces:
    - name: source
  steps:
    - name: remove
      image: alpine:3
      env:
        - name: WORKSPACE_SOURCE_PATH
          value: $(workspaces.source.path)
      workingDir: $(workspaces.source.path)
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
      script: |
        #!/usr/bin/env sh
        set -eu
        echo "Removing all files from ${WORKSPACE_SOURCE_PATH} ..."
        if [ -d "${WORKSPACE_SOURCE_PATH}" ] ; then
          rm -rf "${WORKSPACE_SOURCE_PATH:?}"/*
          rm -rf "${WORKSPACE_SOURCE_PATH}"/.[!.]*
          rm -rf "${WORKSPACE_SOURCE_PATH}"/..?*
        fi

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: maven-test
spec:
  params:
    - name: maven-args
      description: Arguments to pass to maven test
      type: string
      default: "test"
    - name: maven-settings-xml
      description: The contents of the settings.xml file to use for Maven builds
      default: |
        <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
        </settings>
  workspaces:
    - name: source
    - name: maven-settings
      description: Maven settings directory
      optional: true
  steps:
    - name: run-tests
      # Using Maven with JDK 21
      image: maven:3.9.6-eclipse-temurin-21
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/bash
        set -e

        echo "***** Environment *****"
        java -version
        mvn --version
        pwd

        # Create the settings.xml file if a custom one wasn't provided
        if [ ! -f "$(workspaces.maven-settings.path)/settings.xml" ]; then
          mkdir -p $(workspaces.maven-settings.path)
          echo "$(params.maven-settings-xml)" > $(workspaces.maven-settings.path)/settings.xml
        fi

        echo "***** Running Maven Tests with: $(params.maven-args) *****"
        mvn -s $(workspaces.maven-settings.path)/settings.xml $(params.maven-args)

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: checkstyle
spec:
  description: Run checkstyle analysis on Java code
  workspaces:
    - name: source
    - name: maven-settings
      description: Maven settings directory
      optional: true
  steps:
    - name: checkstyle
      # Using Maven with JDK 21
      image: maven:3.9.6-eclipse-temurin-21
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/bash
        set -e
        echo "***** Running Checkstyle *****"
        
        # Run checkstyle with latest Google style
        cat << EOF > checkstyle.xml
        <?xml version="1.0"?>
        <!DOCTYPE module PUBLIC
                "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
                "https://checkstyle.org/dtds/configuration_1_3.dtd">
        <module name="Checker">
            <property name="severity" value="warning"/>
            <module name="TreeWalker">
                <module name="JavadocMethod"/>
                <module name="JavadocType"/>
                <module name="JavadocVariable"/>
                <module name="JavadocStyle"/>
                <module name="ConstantName"/>
                <module name="LocalFinalVariableName"/>
                <module name="LocalVariableName"/>
                <module name="MemberName"/>
                <module name="MethodName"/>
                <module name="PackageName"/>
                <module name="ParameterName"/>
                <module name="StaticVariableName"/>
                <module name="TypeName"/>
                <module name="AvoidStarImport"/>
                <module name="IllegalImport"/>
                <module name="RedundantImport"/>
                <module name="UnusedImports"/>
                <module name="MethodLength"/>
                <module name="ParameterNumber"/>
                <module name="EmptyForIteratorPad"/>
                <module name="MethodParamPad"/>
                <module name="NoWhitespaceAfter"/>
                <module name="NoWhitespaceBefore"/>
                <module name="OperatorWrap"/>
                <module name="ParenPad"/>
                <module name="TypecastParenPad"/>
                <module name="WhitespaceAfter"/>
                <module name="WhitespaceAround"/>
                <module name="ModifierOrder"/>
                <module name="RedundantModifier"/>
                <module name="AvoidNestedBlocks"/>
                <module name="EmptyBlock"/>
                <module name="LeftCurly"/>
                <module name="NeedBraces"/>
                <module name="RightCurly"/>
                <module name="EmptyStatement"/>
                <module name="EqualsHashCode"/>
                <module name="IllegalInstantiation"/>
                <module name="InnerAssignment"/>
                <module name="MagicNumber"/>
                <module name="MissingSwitchDefault"/>
                <module name="SimplifyBooleanExpression"/>
                <module name="SimplifyBooleanReturn"/>
                <module name="DesignForExtension"/>
                <module name="FinalClass"/>
                <module name="HideUtilityClassConstructor"/>
                <module name="InterfaceIsType"/>
                <module name="VisibilityModifier"/>
                <module name="ArrayTypeStyle"/>
                <module name="TodoComment"/>
                <module name="UpperEll"/>
            </module>
        </module>
        EOF
        
        mvn checkstyle:checkstyle -Dcheckstyle.config.location=checkstyle.xml